APP_REPO_URL=https://github.com/anujgupta09/java-maven-sample-app.git
APP_CREDENTIALS_ID=github-java-maven-sample-app-pat
REGISTRY_CREDENTIALS_ID=dockerhub-anujdocker9799
REGISTRY_NAMESPACE=anujdocker9799
REGISTRY_REPO=compvalidator
REGISTRY_IMAGE=docker.io/anujdocker9799/compvalidator
ANCESTRY_REF=origin/main
